classdef checkNotationLedgerTest < matlab.unittest.TestCase
    % Verifies checkNotationLedger.m's two guarantees (no symbol defined in
    % two glossary tables; no symbol used above its own table without a
    % forward-reference note) against small fixture .tex files, plus a
    % regression check that the real report.tex currently passes clean.

    methods (Test)
        function duplicateDefinitionAcrossTablesIsFlagged(obj)
            fixture = [ ...
                "Prose mentioning $x$ nowhere near either table.", ...
                "", ...
                "\begin{table}[H]", ...
                "\begin{tabular}{lll}", ...
                "\toprule", ...
                "Symbol & Code identifier & Meaning \\", ...
                "\midrule", ...
                "$x$ & \textit{X} & first meaning \\", ...
                "\bottomrule", ...
                "\end{tabular}", ...
                "\caption{First.}", ...
                "\label{tab:first-glossary}", ...
                "\end{table}", ...
                "", ...
                "\begin{table}[H]", ...
                "\begin{tabular}{lll}", ...
                "\toprule", ...
                "Symbol & Code identifier & Meaning \\", ...
                "\midrule", ...
                "$x$ & \textit{X} & second, conflicting meaning \\", ...
                "\bottomrule", ...
                "\end{tabular}", ...
                "\caption{Second.}", ...
                "\label{tab:second-glossary}", ...
                "\end{table}"];
            reportPath = obj.writeFixture(fixture);

            [ok, violations] = checkNotationLedger(reportPath);

            obj.verifyFalse(ok);
            obj.verifyTrue(any([violations.kind] == "duplicate-definition"));
        end

        function undocumentedForwardReferenceIsFlagged(obj)
            fixture = [ ...
                "The field obeys $y = 1$ well before the glossary appears.", ...
                "", ...
                "\begin{table}[H]", ...
                "\begin{tabular}{lll}", ...
                "\toprule", ...
                "Symbol & Code identifier & Meaning \\", ...
                "\midrule", ...
                "$y$ & \textit{Y} & a quantity \\", ...
                "\bottomrule", ...
                "\end{tabular}", ...
                "\caption{Glossary.}", ...
                "\label{tab:y-glossary}", ...
                "\end{table}"];
            reportPath = obj.writeFixture(fixture);

            [ok, violations] = checkNotationLedger(reportPath);

            obj.verifyFalse(ok);
            obj.verifyTrue(any([violations.kind] == "undocumented-forward-reference"));
        end

        function forwardReferenceNoteSuppressesViolation(obj)
            fixture = [ ...
                "The field obeys $y = 1$ well before the glossary appears.", ...
                "", ...
                "\begin{table}[H]", ...
                "\begin{tabular}{lll}", ...
                "\toprule", ...
                "Symbol & Code identifier & Meaning \\", ...
                "\midrule", ...
                "$y$ & \textit{Y} & a quantity [forward-reference: introduced above] \\", ...
                "\bottomrule", ...
                "\end{tabular}", ...
                "\caption{Glossary.}", ...
                "\label{tab:y-glossary}", ...
                "\end{table}"];
            reportPath = obj.writeFixture(fixture);

            [ok, violations] = checkNotationLedger(reportPath);

            obj.verifyTrue(ok);
            obj.verifyEmpty(violations);
        end

        function symbolUsedOnlyAfterItsOwnTableIsClean(obj)
            fixture = [ ...
                "\begin{table}[H]", ...
                "\begin{tabular}{lll}", ...
                "\toprule", ...
                "Symbol & Code identifier & Meaning \\", ...
                "\midrule", ...
                "$z$ & \textit{Z} & a quantity \\", ...
                "\bottomrule", ...
                "\end{tabular}", ...
                "\caption{Glossary.}", ...
                "\label{tab:z-glossary}", ...
                "\end{table}", ...
                "", ...
                "Only used afterwards, as $z=2$."];
            reportPath = obj.writeFixture(fixture);

            [ok, violations] = checkNotationLedger(reportPath);

            obj.verifyTrue(ok);
            obj.verifyEmpty(violations);
        end

        function actualReportPassesCleanly(obj)
            reportPath = fullfile(fileparts(mfilename('fullpath')), "report.tex");

            [ok, violations] = checkNotationLedger(reportPath);

            obj.verifyTrue(ok, sprintf("%d notation-ledger violation(s) in report.tex", numel(violations)));
        end
    end

    methods (Access = private)
        function reportPath = writeFixture(obj, lines)
            reportPath = string(tempname) + ".tex";
            obj.addTeardown(@() delete(reportPath));
            fid = fopen(reportPath, "w");
            fprintf(fid, "%s\n", lines);
            fclose(fid);
        end
    end
end
